### ISSUE TITLE
winerror 87

### ISSUE THREAD

**Issue by kwinners** [infinigrove/SR700-Artisan-PDServer#3]
It looks like there's an issue with Windows 10.  The code compiles and runs, but throws out a Winerror 87 out when I try to load the start server command.  It outputs the following.

C:\Coffee\sr700\SR700-Artisan-PDServer>python SAPDServer.py
Not starting broadcast server for localhost.
NS running on localhost:9090 (127.0.0.1)
Warning: HMAC key not set. Anyone can connect to this server!
URI = PYRO:Pyro.NameServer@localhost:9090
Traceback (most recent call last):
  File "SAPDServer.py", line 65, in <module>
    r = Roaster()
  File "SAPDServer.py", line 18, in __init__
    self.update_data, self.next_state, thermostat=True)
  File "c:\python37\lib\site-packages\freshroastsr700\__init__.py", line 146, in __init__
    self.time_process.start()
  File "c:\python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\python37\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects
PS C:\Coffee\sr700\SR700-Artisan-PDServer> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python37\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\python37\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect

**Comment by infinigrove** [comment]
I believe this is an issue with Python 3.7.X.  I recommend using Python 3.5.X.
